// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dzhyun.stockpoolincome.proto

package com.dzhyun.proto;

public final class DzhyunStockpoolincome {
  private DzhyunStockpoolincome() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StockPoolInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string Name = 1;
    /**
     * <code>required string Name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string Name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string Name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional string Date = 2;
    /**
     * <code>optional string Date = 2;</code>
     */
    boolean hasDate();
    /**
     * <code>optional string Date = 2;</code>
     */
    java.lang.String getDate();
    /**
     * <code>optional string Date = 2;</code>
     */
    com.google.protobuf.ByteString
        getDateBytes();

    // optional uint64 RunDay = 3;
    /**
     * <code>optional uint64 RunDay = 3;</code>
     */
    boolean hasRunDay();
    /**
     * <code>optional uint64 RunDay = 3;</code>
     */
    long getRunDay();

    // optional int64 Income = 4;
    /**
     * <code>optional int64 Income = 4;</code>
     */
    boolean hasIncome();
    /**
     * <code>optional int64 Income = 4;</code>
     */
    long getIncome();

    // optional int64 TotalIncome = 5;
    /**
     * <code>optional int64 TotalIncome = 5;</code>
     */
    boolean hasTotalIncome();
    /**
     * <code>optional int64 TotalIncome = 5;</code>
     */
    long getTotalIncome();

    // optional uint64 TotalTransTimes = 6;
    /**
     * <code>optional uint64 TotalTransTimes = 6;</code>
     */
    boolean hasTotalTransTimes();
    /**
     * <code>optional uint64 TotalTransTimes = 6;</code>
     */
    long getTotalTransTimes();

    // optional uint64 TotalWinTimes = 7;
    /**
     * <code>optional uint64 TotalWinTimes = 7;</code>
     */
    boolean hasTotalWinTimes();
    /**
     * <code>optional uint64 TotalWinTimes = 7;</code>
     */
    long getTotalWinTimes();

    // optional string WinPercent = 8;
    /**
     * <code>optional string WinPercent = 8;</code>
     */
    boolean hasWinPercent();
    /**
     * <code>optional string WinPercent = 8;</code>
     */
    java.lang.String getWinPercent();
    /**
     * <code>optional string WinPercent = 8;</code>
     */
    com.google.protobuf.ByteString
        getWinPercentBytes();

    // optional int64 TotalProfit = 9;
    /**
     * <code>optional int64 TotalProfit = 9;</code>
     */
    boolean hasTotalProfit();
    /**
     * <code>optional int64 TotalProfit = 9;</code>
     */
    long getTotalProfit();

    // optional int64 TotalLoss = 10;
    /**
     * <code>optional int64 TotalLoss = 10;</code>
     */
    boolean hasTotalLoss();
    /**
     * <code>optional int64 TotalLoss = 10;</code>
     */
    long getTotalLoss();

    // optional string Ratio = 11;
    /**
     * <code>optional string Ratio = 11;</code>
     */
    boolean hasRatio();
    /**
     * <code>optional string Ratio = 11;</code>
     */
    java.lang.String getRatio();
    /**
     * <code>optional string Ratio = 11;</code>
     */
    com.google.protobuf.ByteString
        getRatioBytes();

    // optional uint64 TotalStockSold = 12;
    /**
     * <code>optional uint64 TotalStockSold = 12;</code>
     */
    boolean hasTotalStockSold();
    /**
     * <code>optional uint64 TotalStockSold = 12;</code>
     */
    long getTotalStockSold();

    // optional uint64 TotalStockHold = 13;
    /**
     * <code>optional uint64 TotalStockHold = 13;</code>
     */
    boolean hasTotalStockHold();
    /**
     * <code>optional uint64 TotalStockHold = 13;</code>
     */
    long getTotalStockHold();

    // optional int64 AvgHoldDay = 14;
    /**
     * <code>optional int64 AvgHoldDay = 14;</code>
     */
    boolean hasAvgHoldDay();
    /**
     * <code>optional int64 AvgHoldDay = 14;</code>
     */
    long getAvgHoldDay();
  }
  /**
   * Protobuf type {@code dzhyun.StockPoolInfo}
   */
  public static final class StockPoolInfo extends
      com.google.protobuf.GeneratedMessage
      implements StockPoolInfoOrBuilder {
    // Use StockPoolInfo.newBuilder() to construct.
    private StockPoolInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StockPoolInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StockPoolInfo defaultInstance;
    public static StockPoolInfo getDefaultInstance() {
      return defaultInstance;
    }

    public StockPoolInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StockPoolInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              date_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              runDay_ = input.readUInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              income_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              totalIncome_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              totalTransTimes_ = input.readUInt64();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              totalWinTimes_ = input.readUInt64();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              winPercent_ = input.readBytes();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              totalProfit_ = input.readInt64();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              totalLoss_ = input.readInt64();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000400;
              ratio_ = input.readBytes();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              totalStockSold_ = input.readUInt64();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              totalStockHold_ = input.readUInt64();
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              avgHoldDay_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dzhyun.proto.DzhyunStockpoolincome.internal_static_dzhyun_StockPoolInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dzhyun.proto.DzhyunStockpoolincome.internal_static_dzhyun_StockPoolInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dzhyun.proto.DzhyunStockpoolincome.StockPoolInfo.class, com.dzhyun.proto.DzhyunStockpoolincome.StockPoolInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<StockPoolInfo> PARSER =
        new com.google.protobuf.AbstractParser<StockPoolInfo>() {
      public StockPoolInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StockPoolInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StockPoolInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string Name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string Name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string Name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string Date = 2;
    public static final int DATE_FIELD_NUMBER = 2;
    private java.lang.Object date_;
    /**
     * <code>optional string Date = 2;</code>
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string Date = 2;</code>
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          date_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string Date = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional uint64 RunDay = 3;
    public static final int RUNDAY_FIELD_NUMBER = 3;
    private long runDay_;
    /**
     * <code>optional uint64 RunDay = 3;</code>
     */
    public boolean hasRunDay() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint64 RunDay = 3;</code>
     */
    public long getRunDay() {
      return runDay_;
    }

    // optional int64 Income = 4;
    public static final int INCOME_FIELD_NUMBER = 4;
    private long income_;
    /**
     * <code>optional int64 Income = 4;</code>
     */
    public boolean hasIncome() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 Income = 4;</code>
     */
    public long getIncome() {
      return income_;
    }

    // optional int64 TotalIncome = 5;
    public static final int TOTALINCOME_FIELD_NUMBER = 5;
    private long totalIncome_;
    /**
     * <code>optional int64 TotalIncome = 5;</code>
     */
    public boolean hasTotalIncome() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 TotalIncome = 5;</code>
     */
    public long getTotalIncome() {
      return totalIncome_;
    }

    // optional uint64 TotalTransTimes = 6;
    public static final int TOTALTRANSTIMES_FIELD_NUMBER = 6;
    private long totalTransTimes_;
    /**
     * <code>optional uint64 TotalTransTimes = 6;</code>
     */
    public boolean hasTotalTransTimes() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional uint64 TotalTransTimes = 6;</code>
     */
    public long getTotalTransTimes() {
      return totalTransTimes_;
    }

    // optional uint64 TotalWinTimes = 7;
    public static final int TOTALWINTIMES_FIELD_NUMBER = 7;
    private long totalWinTimes_;
    /**
     * <code>optional uint64 TotalWinTimes = 7;</code>
     */
    public boolean hasTotalWinTimes() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional uint64 TotalWinTimes = 7;</code>
     */
    public long getTotalWinTimes() {
      return totalWinTimes_;
    }

    // optional string WinPercent = 8;
    public static final int WINPERCENT_FIELD_NUMBER = 8;
    private java.lang.Object winPercent_;
    /**
     * <code>optional string WinPercent = 8;</code>
     */
    public boolean hasWinPercent() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional string WinPercent = 8;</code>
     */
    public java.lang.String getWinPercent() {
      java.lang.Object ref = winPercent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          winPercent_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string WinPercent = 8;</code>
     */
    public com.google.protobuf.ByteString
        getWinPercentBytes() {
      java.lang.Object ref = winPercent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        winPercent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int64 TotalProfit = 9;
    public static final int TOTALPROFIT_FIELD_NUMBER = 9;
    private long totalProfit_;
    /**
     * <code>optional int64 TotalProfit = 9;</code>
     */
    public boolean hasTotalProfit() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int64 TotalProfit = 9;</code>
     */
    public long getTotalProfit() {
      return totalProfit_;
    }

    // optional int64 TotalLoss = 10;
    public static final int TOTALLOSS_FIELD_NUMBER = 10;
    private long totalLoss_;
    /**
     * <code>optional int64 TotalLoss = 10;</code>
     */
    public boolean hasTotalLoss() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional int64 TotalLoss = 10;</code>
     */
    public long getTotalLoss() {
      return totalLoss_;
    }

    // optional string Ratio = 11;
    public static final int RATIO_FIELD_NUMBER = 11;
    private java.lang.Object ratio_;
    /**
     * <code>optional string Ratio = 11;</code>
     */
    public boolean hasRatio() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional string Ratio = 11;</code>
     */
    public java.lang.String getRatio() {
      java.lang.Object ref = ratio_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ratio_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string Ratio = 11;</code>
     */
    public com.google.protobuf.ByteString
        getRatioBytes() {
      java.lang.Object ref = ratio_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ratio_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional uint64 TotalStockSold = 12;
    public static final int TOTALSTOCKSOLD_FIELD_NUMBER = 12;
    private long totalStockSold_;
    /**
     * <code>optional uint64 TotalStockSold = 12;</code>
     */
    public boolean hasTotalStockSold() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional uint64 TotalStockSold = 12;</code>
     */
    public long getTotalStockSold() {
      return totalStockSold_;
    }

    // optional uint64 TotalStockHold = 13;
    public static final int TOTALSTOCKHOLD_FIELD_NUMBER = 13;
    private long totalStockHold_;
    /**
     * <code>optional uint64 TotalStockHold = 13;</code>
     */
    public boolean hasTotalStockHold() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional uint64 TotalStockHold = 13;</code>
     */
    public long getTotalStockHold() {
      return totalStockHold_;
    }

    // optional int64 AvgHoldDay = 14;
    public static final int AVGHOLDDAY_FIELD_NUMBER = 14;
    private long avgHoldDay_;
    /**
     * <code>optional int64 AvgHoldDay = 14;</code>
     */
    public boolean hasAvgHoldDay() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional int64 AvgHoldDay = 14;</code>
     */
    public long getAvgHoldDay() {
      return avgHoldDay_;
    }

    private void initFields() {
      name_ = "";
      date_ = "";
      runDay_ = 0L;
      income_ = 0L;
      totalIncome_ = 0L;
      totalTransTimes_ = 0L;
      totalWinTimes_ = 0L;
      winPercent_ = "";
      totalProfit_ = 0L;
      totalLoss_ = 0L;
      ratio_ = "";
      totalStockSold_ = 0L;
      totalStockHold_ = 0L;
      avgHoldDay_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDateBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, runDay_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, income_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, totalIncome_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt64(6, totalTransTimes_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt64(7, totalWinTimes_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getWinPercentBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt64(9, totalProfit_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt64(10, totalLoss_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getRatioBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeUInt64(12, totalStockSold_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeUInt64(13, totalStockHold_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeInt64(14, avgHoldDay_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDateBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, runDay_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, income_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, totalIncome_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, totalTransTimes_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, totalWinTimes_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getWinPercentBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, totalProfit_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, totalLoss_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getRatioBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(12, totalStockSold_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(13, totalStockHold_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(14, avgHoldDay_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.dzhyun.proto.DzhyunStockpoolincome.StockPoolInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dzhyun.proto.DzhyunStockpoolincome.StockPoolInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dzhyun.proto.DzhyunStockpoolincome.StockPoolInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dzhyun.proto.DzhyunStockpoolincome.StockPoolInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dzhyun.proto.DzhyunStockpoolincome.StockPoolInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dzhyun.proto.DzhyunStockpoolincome.StockPoolInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.dzhyun.proto.DzhyunStockpoolincome.StockPoolInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.dzhyun.proto.DzhyunStockpoolincome.StockPoolInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.dzhyun.proto.DzhyunStockpoolincome.StockPoolInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dzhyun.proto.DzhyunStockpoolincome.StockPoolInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dzhyun.proto.DzhyunStockpoolincome.StockPoolInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dzhyun.StockPoolInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.dzhyun.proto.DzhyunStockpoolincome.StockPoolInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dzhyun.proto.DzhyunStockpoolincome.internal_static_dzhyun_StockPoolInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dzhyun.proto.DzhyunStockpoolincome.internal_static_dzhyun_StockPoolInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dzhyun.proto.DzhyunStockpoolincome.StockPoolInfo.class, com.dzhyun.proto.DzhyunStockpoolincome.StockPoolInfo.Builder.class);
      }

      // Construct using com.dzhyun.proto.DzhyunStockpoolincome.StockPoolInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        date_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        runDay_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        income_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        totalIncome_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        totalTransTimes_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        totalWinTimes_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        winPercent_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        totalProfit_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000100);
        totalLoss_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000200);
        ratio_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        totalStockSold_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000800);
        totalStockHold_ = 0L;
        bitField0_ = (bitField0_ & ~0x00001000);
        avgHoldDay_ = 0L;
        bitField0_ = (bitField0_ & ~0x00002000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dzhyun.proto.DzhyunStockpoolincome.internal_static_dzhyun_StockPoolInfo_descriptor;
      }

      public com.dzhyun.proto.DzhyunStockpoolincome.StockPoolInfo getDefaultInstanceForType() {
        return com.dzhyun.proto.DzhyunStockpoolincome.StockPoolInfo.getDefaultInstance();
      }

      public com.dzhyun.proto.DzhyunStockpoolincome.StockPoolInfo build() {
        com.dzhyun.proto.DzhyunStockpoolincome.StockPoolInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dzhyun.proto.DzhyunStockpoolincome.StockPoolInfo buildPartial() {
        com.dzhyun.proto.DzhyunStockpoolincome.StockPoolInfo result = new com.dzhyun.proto.DzhyunStockpoolincome.StockPoolInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.runDay_ = runDay_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.income_ = income_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.totalIncome_ = totalIncome_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.totalTransTimes_ = totalTransTimes_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.totalWinTimes_ = totalWinTimes_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.winPercent_ = winPercent_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.totalProfit_ = totalProfit_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.totalLoss_ = totalLoss_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.ratio_ = ratio_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.totalStockSold_ = totalStockSold_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.totalStockHold_ = totalStockHold_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.avgHoldDay_ = avgHoldDay_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dzhyun.proto.DzhyunStockpoolincome.StockPoolInfo) {
          return mergeFrom((com.dzhyun.proto.DzhyunStockpoolincome.StockPoolInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dzhyun.proto.DzhyunStockpoolincome.StockPoolInfo other) {
        if (other == com.dzhyun.proto.DzhyunStockpoolincome.StockPoolInfo.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasDate()) {
          bitField0_ |= 0x00000002;
          date_ = other.date_;
          onChanged();
        }
        if (other.hasRunDay()) {
          setRunDay(other.getRunDay());
        }
        if (other.hasIncome()) {
          setIncome(other.getIncome());
        }
        if (other.hasTotalIncome()) {
          setTotalIncome(other.getTotalIncome());
        }
        if (other.hasTotalTransTimes()) {
          setTotalTransTimes(other.getTotalTransTimes());
        }
        if (other.hasTotalWinTimes()) {
          setTotalWinTimes(other.getTotalWinTimes());
        }
        if (other.hasWinPercent()) {
          bitField0_ |= 0x00000080;
          winPercent_ = other.winPercent_;
          onChanged();
        }
        if (other.hasTotalProfit()) {
          setTotalProfit(other.getTotalProfit());
        }
        if (other.hasTotalLoss()) {
          setTotalLoss(other.getTotalLoss());
        }
        if (other.hasRatio()) {
          bitField0_ |= 0x00000400;
          ratio_ = other.ratio_;
          onChanged();
        }
        if (other.hasTotalStockSold()) {
          setTotalStockSold(other.getTotalStockSold());
        }
        if (other.hasTotalStockHold()) {
          setTotalStockHold(other.getTotalStockHold());
        }
        if (other.hasAvgHoldDay()) {
          setAvgHoldDay(other.getAvgHoldDay());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dzhyun.proto.DzhyunStockpoolincome.StockPoolInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dzhyun.proto.DzhyunStockpoolincome.StockPoolInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string Name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string Name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string Name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string Name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string Name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string Name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // optional string Date = 2;
      private java.lang.Object date_ = "";
      /**
       * <code>optional string Date = 2;</code>
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string Date = 2;</code>
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string Date = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Date = 2;</code>
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Date = 2;</code>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>optional string Date = 2;</code>
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        date_ = value;
        onChanged();
        return this;
      }

      // optional uint64 RunDay = 3;
      private long runDay_ ;
      /**
       * <code>optional uint64 RunDay = 3;</code>
       */
      public boolean hasRunDay() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint64 RunDay = 3;</code>
       */
      public long getRunDay() {
        return runDay_;
      }
      /**
       * <code>optional uint64 RunDay = 3;</code>
       */
      public Builder setRunDay(long value) {
        bitField0_ |= 0x00000004;
        runDay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 RunDay = 3;</code>
       */
      public Builder clearRunDay() {
        bitField0_ = (bitField0_ & ~0x00000004);
        runDay_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 Income = 4;
      private long income_ ;
      /**
       * <code>optional int64 Income = 4;</code>
       */
      public boolean hasIncome() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 Income = 4;</code>
       */
      public long getIncome() {
        return income_;
      }
      /**
       * <code>optional int64 Income = 4;</code>
       */
      public Builder setIncome(long value) {
        bitField0_ |= 0x00000008;
        income_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 Income = 4;</code>
       */
      public Builder clearIncome() {
        bitField0_ = (bitField0_ & ~0x00000008);
        income_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 TotalIncome = 5;
      private long totalIncome_ ;
      /**
       * <code>optional int64 TotalIncome = 5;</code>
       */
      public boolean hasTotalIncome() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 TotalIncome = 5;</code>
       */
      public long getTotalIncome() {
        return totalIncome_;
      }
      /**
       * <code>optional int64 TotalIncome = 5;</code>
       */
      public Builder setTotalIncome(long value) {
        bitField0_ |= 0x00000010;
        totalIncome_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 TotalIncome = 5;</code>
       */
      public Builder clearTotalIncome() {
        bitField0_ = (bitField0_ & ~0x00000010);
        totalIncome_ = 0L;
        onChanged();
        return this;
      }

      // optional uint64 TotalTransTimes = 6;
      private long totalTransTimes_ ;
      /**
       * <code>optional uint64 TotalTransTimes = 6;</code>
       */
      public boolean hasTotalTransTimes() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional uint64 TotalTransTimes = 6;</code>
       */
      public long getTotalTransTimes() {
        return totalTransTimes_;
      }
      /**
       * <code>optional uint64 TotalTransTimes = 6;</code>
       */
      public Builder setTotalTransTimes(long value) {
        bitField0_ |= 0x00000020;
        totalTransTimes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 TotalTransTimes = 6;</code>
       */
      public Builder clearTotalTransTimes() {
        bitField0_ = (bitField0_ & ~0x00000020);
        totalTransTimes_ = 0L;
        onChanged();
        return this;
      }

      // optional uint64 TotalWinTimes = 7;
      private long totalWinTimes_ ;
      /**
       * <code>optional uint64 TotalWinTimes = 7;</code>
       */
      public boolean hasTotalWinTimes() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional uint64 TotalWinTimes = 7;</code>
       */
      public long getTotalWinTimes() {
        return totalWinTimes_;
      }
      /**
       * <code>optional uint64 TotalWinTimes = 7;</code>
       */
      public Builder setTotalWinTimes(long value) {
        bitField0_ |= 0x00000040;
        totalWinTimes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 TotalWinTimes = 7;</code>
       */
      public Builder clearTotalWinTimes() {
        bitField0_ = (bitField0_ & ~0x00000040);
        totalWinTimes_ = 0L;
        onChanged();
        return this;
      }

      // optional string WinPercent = 8;
      private java.lang.Object winPercent_ = "";
      /**
       * <code>optional string WinPercent = 8;</code>
       */
      public boolean hasWinPercent() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string WinPercent = 8;</code>
       */
      public java.lang.String getWinPercent() {
        java.lang.Object ref = winPercent_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          winPercent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string WinPercent = 8;</code>
       */
      public com.google.protobuf.ByteString
          getWinPercentBytes() {
        java.lang.Object ref = winPercent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          winPercent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string WinPercent = 8;</code>
       */
      public Builder setWinPercent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        winPercent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string WinPercent = 8;</code>
       */
      public Builder clearWinPercent() {
        bitField0_ = (bitField0_ & ~0x00000080);
        winPercent_ = getDefaultInstance().getWinPercent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string WinPercent = 8;</code>
       */
      public Builder setWinPercentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        winPercent_ = value;
        onChanged();
        return this;
      }

      // optional int64 TotalProfit = 9;
      private long totalProfit_ ;
      /**
       * <code>optional int64 TotalProfit = 9;</code>
       */
      public boolean hasTotalProfit() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int64 TotalProfit = 9;</code>
       */
      public long getTotalProfit() {
        return totalProfit_;
      }
      /**
       * <code>optional int64 TotalProfit = 9;</code>
       */
      public Builder setTotalProfit(long value) {
        bitField0_ |= 0x00000100;
        totalProfit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 TotalProfit = 9;</code>
       */
      public Builder clearTotalProfit() {
        bitField0_ = (bitField0_ & ~0x00000100);
        totalProfit_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 TotalLoss = 10;
      private long totalLoss_ ;
      /**
       * <code>optional int64 TotalLoss = 10;</code>
       */
      public boolean hasTotalLoss() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional int64 TotalLoss = 10;</code>
       */
      public long getTotalLoss() {
        return totalLoss_;
      }
      /**
       * <code>optional int64 TotalLoss = 10;</code>
       */
      public Builder setTotalLoss(long value) {
        bitField0_ |= 0x00000200;
        totalLoss_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 TotalLoss = 10;</code>
       */
      public Builder clearTotalLoss() {
        bitField0_ = (bitField0_ & ~0x00000200);
        totalLoss_ = 0L;
        onChanged();
        return this;
      }

      // optional string Ratio = 11;
      private java.lang.Object ratio_ = "";
      /**
       * <code>optional string Ratio = 11;</code>
       */
      public boolean hasRatio() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional string Ratio = 11;</code>
       */
      public java.lang.String getRatio() {
        java.lang.Object ref = ratio_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          ratio_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string Ratio = 11;</code>
       */
      public com.google.protobuf.ByteString
          getRatioBytes() {
        java.lang.Object ref = ratio_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ratio_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string Ratio = 11;</code>
       */
      public Builder setRatio(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        ratio_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string Ratio = 11;</code>
       */
      public Builder clearRatio() {
        bitField0_ = (bitField0_ & ~0x00000400);
        ratio_ = getDefaultInstance().getRatio();
        onChanged();
        return this;
      }
      /**
       * <code>optional string Ratio = 11;</code>
       */
      public Builder setRatioBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        ratio_ = value;
        onChanged();
        return this;
      }

      // optional uint64 TotalStockSold = 12;
      private long totalStockSold_ ;
      /**
       * <code>optional uint64 TotalStockSold = 12;</code>
       */
      public boolean hasTotalStockSold() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional uint64 TotalStockSold = 12;</code>
       */
      public long getTotalStockSold() {
        return totalStockSold_;
      }
      /**
       * <code>optional uint64 TotalStockSold = 12;</code>
       */
      public Builder setTotalStockSold(long value) {
        bitField0_ |= 0x00000800;
        totalStockSold_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 TotalStockSold = 12;</code>
       */
      public Builder clearTotalStockSold() {
        bitField0_ = (bitField0_ & ~0x00000800);
        totalStockSold_ = 0L;
        onChanged();
        return this;
      }

      // optional uint64 TotalStockHold = 13;
      private long totalStockHold_ ;
      /**
       * <code>optional uint64 TotalStockHold = 13;</code>
       */
      public boolean hasTotalStockHold() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional uint64 TotalStockHold = 13;</code>
       */
      public long getTotalStockHold() {
        return totalStockHold_;
      }
      /**
       * <code>optional uint64 TotalStockHold = 13;</code>
       */
      public Builder setTotalStockHold(long value) {
        bitField0_ |= 0x00001000;
        totalStockHold_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 TotalStockHold = 13;</code>
       */
      public Builder clearTotalStockHold() {
        bitField0_ = (bitField0_ & ~0x00001000);
        totalStockHold_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 AvgHoldDay = 14;
      private long avgHoldDay_ ;
      /**
       * <code>optional int64 AvgHoldDay = 14;</code>
       */
      public boolean hasAvgHoldDay() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional int64 AvgHoldDay = 14;</code>
       */
      public long getAvgHoldDay() {
        return avgHoldDay_;
      }
      /**
       * <code>optional int64 AvgHoldDay = 14;</code>
       */
      public Builder setAvgHoldDay(long value) {
        bitField0_ |= 0x00002000;
        avgHoldDay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 AvgHoldDay = 14;</code>
       */
      public Builder clearAvgHoldDay() {
        bitField0_ = (bitField0_ & ~0x00002000);
        avgHoldDay_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dzhyun.StockPoolInfo)
    }

    static {
      defaultInstance = new StockPoolInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:dzhyun.StockPoolInfo)
  }

  public interface StockPoolObjIncomeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string Obj = 1;
    /**
     * <code>required string Obj = 1;</code>
     */
    boolean hasObj();
    /**
     * <code>required string Obj = 1;</code>
     */
    java.lang.String getObj();
    /**
     * <code>required string Obj = 1;</code>
     */
    com.google.protobuf.ByteString
        getObjBytes();

    // optional string BuyTime = 2;
    /**
     * <code>optional string BuyTime = 2;</code>
     */
    boolean hasBuyTime();
    /**
     * <code>optional string BuyTime = 2;</code>
     */
    java.lang.String getBuyTime();
    /**
     * <code>optional string BuyTime = 2;</code>
     */
    com.google.protobuf.ByteString
        getBuyTimeBytes();

    // optional int64 BuyPrice = 3;
    /**
     * <code>optional int64 BuyPrice = 3;</code>
     */
    boolean hasBuyPrice();
    /**
     * <code>optional int64 BuyPrice = 3;</code>
     */
    long getBuyPrice();

    // optional int64 IncomeRate = 4;
    /**
     * <code>optional int64 IncomeRate = 4;</code>
     */
    boolean hasIncomeRate();
    /**
     * <code>optional int64 IncomeRate = 4;</code>
     */
    long getIncomeRate();

    // optional uint64 RunDay = 5;
    /**
     * <code>optional uint64 RunDay = 5;</code>
     */
    boolean hasRunDay();
    /**
     * <code>optional uint64 RunDay = 5;</code>
     */
    long getRunDay();

    // optional bool Sold = 6;
    /**
     * <code>optional bool Sold = 6;</code>
     */
    boolean hasSold();
    /**
     * <code>optional bool Sold = 6;</code>
     */
    boolean getSold();
  }
  /**
   * Protobuf type {@code dzhyun.StockPoolObjIncome}
   */
  public static final class StockPoolObjIncome extends
      com.google.protobuf.GeneratedMessage
      implements StockPoolObjIncomeOrBuilder {
    // Use StockPoolObjIncome.newBuilder() to construct.
    private StockPoolObjIncome(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StockPoolObjIncome(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StockPoolObjIncome defaultInstance;
    public static StockPoolObjIncome getDefaultInstance() {
      return defaultInstance;
    }

    public StockPoolObjIncome getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StockPoolObjIncome(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              obj_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              buyTime_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              buyPrice_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              incomeRate_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              runDay_ = input.readUInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              sold_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dzhyun.proto.DzhyunStockpoolincome.internal_static_dzhyun_StockPoolObjIncome_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dzhyun.proto.DzhyunStockpoolincome.internal_static_dzhyun_StockPoolObjIncome_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dzhyun.proto.DzhyunStockpoolincome.StockPoolObjIncome.class, com.dzhyun.proto.DzhyunStockpoolincome.StockPoolObjIncome.Builder.class);
    }

    public static com.google.protobuf.Parser<StockPoolObjIncome> PARSER =
        new com.google.protobuf.AbstractParser<StockPoolObjIncome>() {
      public StockPoolObjIncome parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StockPoolObjIncome(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StockPoolObjIncome> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string Obj = 1;
    public static final int OBJ_FIELD_NUMBER = 1;
    private java.lang.Object obj_;
    /**
     * <code>required string Obj = 1;</code>
     */
    public boolean hasObj() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string Obj = 1;</code>
     */
    public java.lang.String getObj() {
      java.lang.Object ref = obj_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          obj_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string Obj = 1;</code>
     */
    public com.google.protobuf.ByteString
        getObjBytes() {
      java.lang.Object ref = obj_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        obj_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string BuyTime = 2;
    public static final int BUYTIME_FIELD_NUMBER = 2;
    private java.lang.Object buyTime_;
    /**
     * <code>optional string BuyTime = 2;</code>
     */
    public boolean hasBuyTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string BuyTime = 2;</code>
     */
    public java.lang.String getBuyTime() {
      java.lang.Object ref = buyTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          buyTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string BuyTime = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBuyTimeBytes() {
      java.lang.Object ref = buyTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        buyTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int64 BuyPrice = 3;
    public static final int BUYPRICE_FIELD_NUMBER = 3;
    private long buyPrice_;
    /**
     * <code>optional int64 BuyPrice = 3;</code>
     */
    public boolean hasBuyPrice() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 BuyPrice = 3;</code>
     */
    public long getBuyPrice() {
      return buyPrice_;
    }

    // optional int64 IncomeRate = 4;
    public static final int INCOMERATE_FIELD_NUMBER = 4;
    private long incomeRate_;
    /**
     * <code>optional int64 IncomeRate = 4;</code>
     */
    public boolean hasIncomeRate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 IncomeRate = 4;</code>
     */
    public long getIncomeRate() {
      return incomeRate_;
    }

    // optional uint64 RunDay = 5;
    public static final int RUNDAY_FIELD_NUMBER = 5;
    private long runDay_;
    /**
     * <code>optional uint64 RunDay = 5;</code>
     */
    public boolean hasRunDay() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional uint64 RunDay = 5;</code>
     */
    public long getRunDay() {
      return runDay_;
    }

    // optional bool Sold = 6;
    public static final int SOLD_FIELD_NUMBER = 6;
    private boolean sold_;
    /**
     * <code>optional bool Sold = 6;</code>
     */
    public boolean hasSold() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bool Sold = 6;</code>
     */
    public boolean getSold() {
      return sold_;
    }

    private void initFields() {
      obj_ = "";
      buyTime_ = "";
      buyPrice_ = 0L;
      incomeRate_ = 0L;
      runDay_ = 0L;
      sold_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasObj()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getObjBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getBuyTimeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, buyPrice_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, incomeRate_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt64(5, runDay_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(6, sold_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getObjBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getBuyTimeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, buyPrice_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, incomeRate_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, runDay_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, sold_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.dzhyun.proto.DzhyunStockpoolincome.StockPoolObjIncome parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dzhyun.proto.DzhyunStockpoolincome.StockPoolObjIncome parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dzhyun.proto.DzhyunStockpoolincome.StockPoolObjIncome parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dzhyun.proto.DzhyunStockpoolincome.StockPoolObjIncome parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dzhyun.proto.DzhyunStockpoolincome.StockPoolObjIncome parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dzhyun.proto.DzhyunStockpoolincome.StockPoolObjIncome parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.dzhyun.proto.DzhyunStockpoolincome.StockPoolObjIncome parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.dzhyun.proto.DzhyunStockpoolincome.StockPoolObjIncome parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.dzhyun.proto.DzhyunStockpoolincome.StockPoolObjIncome parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dzhyun.proto.DzhyunStockpoolincome.StockPoolObjIncome parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dzhyun.proto.DzhyunStockpoolincome.StockPoolObjIncome prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dzhyun.StockPoolObjIncome}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.dzhyun.proto.DzhyunStockpoolincome.StockPoolObjIncomeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dzhyun.proto.DzhyunStockpoolincome.internal_static_dzhyun_StockPoolObjIncome_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dzhyun.proto.DzhyunStockpoolincome.internal_static_dzhyun_StockPoolObjIncome_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dzhyun.proto.DzhyunStockpoolincome.StockPoolObjIncome.class, com.dzhyun.proto.DzhyunStockpoolincome.StockPoolObjIncome.Builder.class);
      }

      // Construct using com.dzhyun.proto.DzhyunStockpoolincome.StockPoolObjIncome.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        obj_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        buyTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        buyPrice_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        incomeRate_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        runDay_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        sold_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dzhyun.proto.DzhyunStockpoolincome.internal_static_dzhyun_StockPoolObjIncome_descriptor;
      }

      public com.dzhyun.proto.DzhyunStockpoolincome.StockPoolObjIncome getDefaultInstanceForType() {
        return com.dzhyun.proto.DzhyunStockpoolincome.StockPoolObjIncome.getDefaultInstance();
      }

      public com.dzhyun.proto.DzhyunStockpoolincome.StockPoolObjIncome build() {
        com.dzhyun.proto.DzhyunStockpoolincome.StockPoolObjIncome result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dzhyun.proto.DzhyunStockpoolincome.StockPoolObjIncome buildPartial() {
        com.dzhyun.proto.DzhyunStockpoolincome.StockPoolObjIncome result = new com.dzhyun.proto.DzhyunStockpoolincome.StockPoolObjIncome(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.obj_ = obj_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.buyTime_ = buyTime_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.buyPrice_ = buyPrice_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.incomeRate_ = incomeRate_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.runDay_ = runDay_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.sold_ = sold_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dzhyun.proto.DzhyunStockpoolincome.StockPoolObjIncome) {
          return mergeFrom((com.dzhyun.proto.DzhyunStockpoolincome.StockPoolObjIncome)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dzhyun.proto.DzhyunStockpoolincome.StockPoolObjIncome other) {
        if (other == com.dzhyun.proto.DzhyunStockpoolincome.StockPoolObjIncome.getDefaultInstance()) return this;
        if (other.hasObj()) {
          bitField0_ |= 0x00000001;
          obj_ = other.obj_;
          onChanged();
        }
        if (other.hasBuyTime()) {
          bitField0_ |= 0x00000002;
          buyTime_ = other.buyTime_;
          onChanged();
        }
        if (other.hasBuyPrice()) {
          setBuyPrice(other.getBuyPrice());
        }
        if (other.hasIncomeRate()) {
          setIncomeRate(other.getIncomeRate());
        }
        if (other.hasRunDay()) {
          setRunDay(other.getRunDay());
        }
        if (other.hasSold()) {
          setSold(other.getSold());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasObj()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dzhyun.proto.DzhyunStockpoolincome.StockPoolObjIncome parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dzhyun.proto.DzhyunStockpoolincome.StockPoolObjIncome) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string Obj = 1;
      private java.lang.Object obj_ = "";
      /**
       * <code>required string Obj = 1;</code>
       */
      public boolean hasObj() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string Obj = 1;</code>
       */
      public java.lang.String getObj() {
        java.lang.Object ref = obj_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          obj_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string Obj = 1;</code>
       */
      public com.google.protobuf.ByteString
          getObjBytes() {
        java.lang.Object ref = obj_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          obj_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string Obj = 1;</code>
       */
      public Builder setObj(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string Obj = 1;</code>
       */
      public Builder clearObj() {
        bitField0_ = (bitField0_ & ~0x00000001);
        obj_ = getDefaultInstance().getObj();
        onChanged();
        return this;
      }
      /**
       * <code>required string Obj = 1;</code>
       */
      public Builder setObjBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        obj_ = value;
        onChanged();
        return this;
      }

      // optional string BuyTime = 2;
      private java.lang.Object buyTime_ = "";
      /**
       * <code>optional string BuyTime = 2;</code>
       */
      public boolean hasBuyTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string BuyTime = 2;</code>
       */
      public java.lang.String getBuyTime() {
        java.lang.Object ref = buyTime_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          buyTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string BuyTime = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBuyTimeBytes() {
        java.lang.Object ref = buyTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          buyTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string BuyTime = 2;</code>
       */
      public Builder setBuyTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        buyTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string BuyTime = 2;</code>
       */
      public Builder clearBuyTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        buyTime_ = getDefaultInstance().getBuyTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string BuyTime = 2;</code>
       */
      public Builder setBuyTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        buyTime_ = value;
        onChanged();
        return this;
      }

      // optional int64 BuyPrice = 3;
      private long buyPrice_ ;
      /**
       * <code>optional int64 BuyPrice = 3;</code>
       */
      public boolean hasBuyPrice() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 BuyPrice = 3;</code>
       */
      public long getBuyPrice() {
        return buyPrice_;
      }
      /**
       * <code>optional int64 BuyPrice = 3;</code>
       */
      public Builder setBuyPrice(long value) {
        bitField0_ |= 0x00000004;
        buyPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 BuyPrice = 3;</code>
       */
      public Builder clearBuyPrice() {
        bitField0_ = (bitField0_ & ~0x00000004);
        buyPrice_ = 0L;
        onChanged();
        return this;
      }

      // optional int64 IncomeRate = 4;
      private long incomeRate_ ;
      /**
       * <code>optional int64 IncomeRate = 4;</code>
       */
      public boolean hasIncomeRate() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 IncomeRate = 4;</code>
       */
      public long getIncomeRate() {
        return incomeRate_;
      }
      /**
       * <code>optional int64 IncomeRate = 4;</code>
       */
      public Builder setIncomeRate(long value) {
        bitField0_ |= 0x00000008;
        incomeRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 IncomeRate = 4;</code>
       */
      public Builder clearIncomeRate() {
        bitField0_ = (bitField0_ & ~0x00000008);
        incomeRate_ = 0L;
        onChanged();
        return this;
      }

      // optional uint64 RunDay = 5;
      private long runDay_ ;
      /**
       * <code>optional uint64 RunDay = 5;</code>
       */
      public boolean hasRunDay() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional uint64 RunDay = 5;</code>
       */
      public long getRunDay() {
        return runDay_;
      }
      /**
       * <code>optional uint64 RunDay = 5;</code>
       */
      public Builder setRunDay(long value) {
        bitField0_ |= 0x00000010;
        runDay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 RunDay = 5;</code>
       */
      public Builder clearRunDay() {
        bitField0_ = (bitField0_ & ~0x00000010);
        runDay_ = 0L;
        onChanged();
        return this;
      }

      // optional bool Sold = 6;
      private boolean sold_ ;
      /**
       * <code>optional bool Sold = 6;</code>
       */
      public boolean hasSold() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bool Sold = 6;</code>
       */
      public boolean getSold() {
        return sold_;
      }
      /**
       * <code>optional bool Sold = 6;</code>
       */
      public Builder setSold(boolean value) {
        bitField0_ |= 0x00000020;
        sold_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool Sold = 6;</code>
       */
      public Builder clearSold() {
        bitField0_ = (bitField0_ & ~0x00000020);
        sold_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dzhyun.StockPoolObjIncome)
    }

    static {
      defaultInstance = new StockPoolObjIncome(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:dzhyun.StockPoolObjIncome)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_dzhyun_StockPoolInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dzhyun_StockPoolInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_dzhyun_StockPoolObjIncome_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dzhyun_StockPoolObjIncome_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034dzhyun.stockpoolincome.proto\022\006dzhyun\"\237" +
      "\002\n\rStockPoolInfo\022\014\n\004Name\030\001 \002(\t\022\014\n\004Date\030\002" +
      " \001(\t\022\016\n\006RunDay\030\003 \001(\004\022\016\n\006Income\030\004 \001(\003\022\023\n\013" +
      "TotalIncome\030\005 \001(\003\022\027\n\017TotalTransTimes\030\006 \001" +
      "(\004\022\025\n\rTotalWinTimes\030\007 \001(\004\022\022\n\nWinPercent\030" +
      "\010 \001(\t\022\023\n\013TotalProfit\030\t \001(\003\022\021\n\tTotalLoss\030" +
      "\n \001(\003\022\r\n\005Ratio\030\013 \001(\t\022\026\n\016TotalStockSold\030\014" +
      " \001(\004\022\026\n\016TotalStockHold\030\r \001(\004\022\022\n\nAvgHoldD" +
      "ay\030\016 \001(\003\"v\n\022StockPoolObjIncome\022\013\n\003Obj\030\001 " +
      "\002(\t\022\017\n\007BuyTime\030\002 \001(\t\022\020\n\010BuyPrice\030\003 \001(\003\022\022",
      "\n\nIncomeRate\030\004 \001(\003\022\016\n\006RunDay\030\005 \001(\004\022\014\n\004So" +
      "ld\030\006 \001(\010B\022\n\020com.dzhyun.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_dzhyun_StockPoolInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_dzhyun_StockPoolInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_dzhyun_StockPoolInfo_descriptor,
              new java.lang.String[] { "Name", "Date", "RunDay", "Income", "TotalIncome", "TotalTransTimes", "TotalWinTimes", "WinPercent", "TotalProfit", "TotalLoss", "Ratio", "TotalStockSold", "TotalStockHold", "AvgHoldDay", });
          internal_static_dzhyun_StockPoolObjIncome_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_dzhyun_StockPoolObjIncome_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_dzhyun_StockPoolObjIncome_descriptor,
              new java.lang.String[] { "Obj", "BuyTime", "BuyPrice", "IncomeRate", "RunDay", "Sold", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
