// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dzhyun.stockincome.proto

package com.dzhyun.proto;

public final class DzhyunStockincome {
  private DzhyunStockincome() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StockIncomeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string IncomeRate = 1;
    /**
     * <code>optional string IncomeRate = 1;</code>
     */
    boolean hasIncomeRate();
    /**
     * <code>optional string IncomeRate = 1;</code>
     */
    java.lang.String getIncomeRate();
    /**
     * <code>optional string IncomeRate = 1;</code>
     */
    com.google.protobuf.ByteString
        getIncomeRateBytes();
  }
  /**
   * Protobuf type {@code dzhyun.StockIncome}
   */
  public static final class StockIncome extends
      com.google.protobuf.GeneratedMessage
      implements StockIncomeOrBuilder {
    // Use StockIncome.newBuilder() to construct.
    private StockIncome(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StockIncome(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StockIncome defaultInstance;
    public static StockIncome getDefaultInstance() {
      return defaultInstance;
    }

    public StockIncome getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StockIncome(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              incomeRate_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dzhyun.proto.DzhyunStockincome.internal_static_dzhyun_StockIncome_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dzhyun.proto.DzhyunStockincome.internal_static_dzhyun_StockIncome_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dzhyun.proto.DzhyunStockincome.StockIncome.class, com.dzhyun.proto.DzhyunStockincome.StockIncome.Builder.class);
    }

    public static com.google.protobuf.Parser<StockIncome> PARSER =
        new com.google.protobuf.AbstractParser<StockIncome>() {
      public StockIncome parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StockIncome(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StockIncome> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string IncomeRate = 1;
    public static final int INCOMERATE_FIELD_NUMBER = 1;
    private java.lang.Object incomeRate_;
    /**
     * <code>optional string IncomeRate = 1;</code>
     */
    public boolean hasIncomeRate() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string IncomeRate = 1;</code>
     */
    public java.lang.String getIncomeRate() {
      java.lang.Object ref = incomeRate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          incomeRate_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string IncomeRate = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIncomeRateBytes() {
      java.lang.Object ref = incomeRate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        incomeRate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      incomeRate_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIncomeRateBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIncomeRateBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.dzhyun.proto.DzhyunStockincome.StockIncome parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dzhyun.proto.DzhyunStockincome.StockIncome parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dzhyun.proto.DzhyunStockincome.StockIncome parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dzhyun.proto.DzhyunStockincome.StockIncome parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dzhyun.proto.DzhyunStockincome.StockIncome parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dzhyun.proto.DzhyunStockincome.StockIncome parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.dzhyun.proto.DzhyunStockincome.StockIncome parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.dzhyun.proto.DzhyunStockincome.StockIncome parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.dzhyun.proto.DzhyunStockincome.StockIncome parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.dzhyun.proto.DzhyunStockincome.StockIncome parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.dzhyun.proto.DzhyunStockincome.StockIncome prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dzhyun.StockIncome}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.dzhyun.proto.DzhyunStockincome.StockIncomeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dzhyun.proto.DzhyunStockincome.internal_static_dzhyun_StockIncome_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dzhyun.proto.DzhyunStockincome.internal_static_dzhyun_StockIncome_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dzhyun.proto.DzhyunStockincome.StockIncome.class, com.dzhyun.proto.DzhyunStockincome.StockIncome.Builder.class);
      }

      // Construct using com.dzhyun.proto.DzhyunStockincome.StockIncome.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        incomeRate_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dzhyun.proto.DzhyunStockincome.internal_static_dzhyun_StockIncome_descriptor;
      }

      public com.dzhyun.proto.DzhyunStockincome.StockIncome getDefaultInstanceForType() {
        return com.dzhyun.proto.DzhyunStockincome.StockIncome.getDefaultInstance();
      }

      public com.dzhyun.proto.DzhyunStockincome.StockIncome build() {
        com.dzhyun.proto.DzhyunStockincome.StockIncome result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.dzhyun.proto.DzhyunStockincome.StockIncome buildPartial() {
        com.dzhyun.proto.DzhyunStockincome.StockIncome result = new com.dzhyun.proto.DzhyunStockincome.StockIncome(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.incomeRate_ = incomeRate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dzhyun.proto.DzhyunStockincome.StockIncome) {
          return mergeFrom((com.dzhyun.proto.DzhyunStockincome.StockIncome)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dzhyun.proto.DzhyunStockincome.StockIncome other) {
        if (other == com.dzhyun.proto.DzhyunStockincome.StockIncome.getDefaultInstance()) return this;
        if (other.hasIncomeRate()) {
          bitField0_ |= 0x00000001;
          incomeRate_ = other.incomeRate_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dzhyun.proto.DzhyunStockincome.StockIncome parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dzhyun.proto.DzhyunStockincome.StockIncome) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string IncomeRate = 1;
      private java.lang.Object incomeRate_ = "";
      /**
       * <code>optional string IncomeRate = 1;</code>
       */
      public boolean hasIncomeRate() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string IncomeRate = 1;</code>
       */
      public java.lang.String getIncomeRate() {
        java.lang.Object ref = incomeRate_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          incomeRate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string IncomeRate = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIncomeRateBytes() {
        java.lang.Object ref = incomeRate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          incomeRate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string IncomeRate = 1;</code>
       */
      public Builder setIncomeRate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        incomeRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string IncomeRate = 1;</code>
       */
      public Builder clearIncomeRate() {
        bitField0_ = (bitField0_ & ~0x00000001);
        incomeRate_ = getDefaultInstance().getIncomeRate();
        onChanged();
        return this;
      }
      /**
       * <code>optional string IncomeRate = 1;</code>
       */
      public Builder setIncomeRateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        incomeRate_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dzhyun.StockIncome)
    }

    static {
      defaultInstance = new StockIncome(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:dzhyun.StockIncome)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_dzhyun_StockIncome_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dzhyun_StockIncome_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030dzhyun.stockincome.proto\022\006dzhyun\"!\n\013St" +
      "ockIncome\022\022\n\nIncomeRate\030\001 \001(\tB\022\n\020com.dzh" +
      "yun.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_dzhyun_StockIncome_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_dzhyun_StockIncome_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_dzhyun_StockIncome_descriptor,
              new java.lang.String[] { "IncomeRate", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
